
services:
  postgres:
    image: postgres:latest
    container_name: codetion_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django:
    tty: true
    image: python:latest
    
    container_name: codetion
    working_dir: /app
    command: /app/entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres

volumes:
  postgres_data:
