
services:
  postgres:
    image: postgres:latest
    container_name: codetion_postgres
    environment:
      POSTGRES_DB: codetion
      POSTGRES_USER: codetion
      POSTGRES_PASSWORD: codetion
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    image: python:latest
    
    container_name: codetion
    working_dir: /app
    command: /app/entrypoint.sh
    ports:
      - "8003:8003"
    volumes:
      - .:/app
    depends_on:
      - postgres
volumes:
  postgres_data:
