# Generated by Django 5.0.1 on 2024-01-21 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='unique_code',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='unique_code',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='submission_time',
        ),
    ]
