# Generated by Django 5.0.1 on 2024-01-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_remove_submission_quiz_submission_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredparticipant',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
