# Generated by Django 4.1.2 on 2024-01-18 06:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="jwt_token",
        ),
    ]
